### PR TITLE
Introduce DB_NAME env var to configure the database name

### PR DESCRIPTION
**Pull request by willdurand**
Like https://github.com/mozilla-services/bouncer-admin/pull/141 but with circle checks :)

### CODE REVIEW

**Comment by jbuck** [comment]
I don't know how painful these checks will be to fix up - if it's ridiculous, then we can merge this and do that work in a separate PR

**Comment by jbuck** [comment]
(and if I'm being honest, it is probably better to switch to GitHub actions)

**Comment by willdurand** [comment]
Looks like we only need to upgrade black.

**Comment by willdurand** [comment]
I'd vote for a separate PR, maybe merge ahead of this one.

**Comment by willdurand** [comment]
https://github.com/mozilla-services/bouncer-admin/pull/143

**Review by jbuck — APPROVED** [review]

**Comment by willdurand** [comment]
> You’re not [authorized](https://docs.github.com/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/about-protected-branches) to merge this pull request.

Please merge for me, thank you!

**Comment by jbuck** [comment]
Try now? just turned off that rule

**Comment by willdurand** [comment]
Still not authorized.

**Pull request merged**
